_target_: models.vit_encoder.ViTEncoder
image_size: ${img_size}
patch_size: 14
dim: ${embed_dim}
depth: 12
heads: 3
mlp_dim: 768
dim_head: 64
dropout: 0.0
emb_dropout: 0.0
feature: patch        # patch tokens (latent_ndim=2, num_patches=(img/patch)**2)
proj_hidden: 2048
proj_dim: ${embed_dim}
name: vit_scratch
